__title__ = "minenbt"
__description__ = "lib and cli script to handle Minecraft savefiles"
__url__ = "https://github.com/timendum/minenbt/"
__version__ = "1.0.0"
__author__ = "timendum"
__license__ = "GNU General Public License v3.0"
